-- 0001_init.sql — core schema.
--
-- Conventions:
--   * UUID primary keys generated by the application (no pgcrypto dependency).
--   * timestamptz everywhere; the connector normalizes to UTC.
--   * Uniqueness expresses idempotency: redelivering the same event or
--     reusing the same idempotency key is a no-op, not an error.

CREATE TABLE devices (
    id           uuid PRIMARY KEY,
    provider     text NOT NULL,
    external_id  text NOT NULL,
    name         text NOT NULL DEFAULT '',
    status       text NOT NULL DEFAULT 'UNKNOWN',
    app_version  text NOT NULL DEFAULT '',
    last_seen_at timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    -- A device is identified by who owns it and what they call it.
    CONSTRAINT devices_provider_external_unique UNIQUE (provider, external_id)
);

CREATE TABLE telemetry (
    id                   uuid PRIMARY KEY,
    device_id            uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    reported_at          timestamptz NOT NULL,
    received_at          timestamptz NOT NULL,
    monitoring_status    text NOT NULL,
    model_status         text NOT NULL DEFAULT '',
    inference_latency_ms bigint NOT NULL DEFAULT 0 CHECK (inference_latency_ms >= 0),
    processed_fps        integer NOT NULL DEFAULT 0 CHECK (processed_fps >= 0),
    dropped_frames       bigint NOT NULL DEFAULT 0 CHECK (dropped_frames >= 0),
    confirmed_events     bigint NOT NULL DEFAULT 0 CHECK (confirmed_events >= 0),
    app_version          text NOT NULL DEFAULT ''
);
-- Telemetry is read as "latest N for a device".
CREATE INDEX telemetry_device_reported_idx ON telemetry (device_id, reported_at DESC);

CREATE TABLE hazard_events (
    id            uuid PRIMARY KEY,
    device_id     uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    source        text NOT NULL,
    dedup_key     text NOT NULL,
    type          text NOT NULL,
    confidence    double precision NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    first_seen_at timestamptz NOT NULL,
    confirmed_at  timestamptz NOT NULL,
    received_at   timestamptz NOT NULL,
    -- Idempotency: the same source may deliver the same event many times.
    CONSTRAINT hazard_events_source_dedup_unique UNIQUE (source, dedup_key)
);
CREATE INDEX hazard_events_received_idx ON hazard_events (received_at DESC);
CREATE INDEX hazard_events_device_idx ON hazard_events (device_id, received_at DESC);

CREATE TABLE commands (
    id              uuid PRIMARY KEY,
    device_id       uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    type            text NOT NULL,
    payload         jsonb NOT NULL DEFAULT '{}'::jsonb,
    idempotency_key text NOT NULL DEFAULT '',
    state           text NOT NULL DEFAULT 'PENDING',
    result_message  text NOT NULL DEFAULT '',
    created_at      timestamptz NOT NULL DEFAULT now(),
    delivered_at    timestamptz,
    completed_at    timestamptz,
    expires_at      timestamptz NOT NULL
);
-- Retrying SendCommand with the same key must not enqueue twice.
CREATE UNIQUE INDEX commands_device_idem_unique
    ON commands (device_id, idempotency_key) WHERE idempotency_key <> '';
-- The device poll reads "pending commands for me, oldest first".
CREATE INDEX commands_pending_idx ON commands (device_id, created_at) WHERE state = 'PENDING';
-- The reaper scans for expired undelivered/unacknowledged commands.
CREATE INDEX commands_expiry_idx ON commands (expires_at) WHERE state IN ('PENDING','DELIVERED');

CREATE TABLE provider_connections (
    id                 uuid PRIMARY KEY,
    provider           text NOT NULL UNIQUE,
    base_url           text NOT NULL DEFAULT '',
    -- Token material is AES-256-GCM ciphertext, never plaintext.
    access_token_enc   bytea,
    refresh_token_enc  bytea,
    token_expiry       timestamptz,
    webhook_secret_enc bytea,
    status             text NOT NULL DEFAULT 'ACTIVE',
    updated_at         timestamptz NOT NULL DEFAULT now()
);

-- Every accepted webhook delivery, for duplicate detection across kinds
-- (hazard events, heartbeats). Insert-first with ON CONFLICT DO NOTHING is
-- the idempotency gate.
CREATE TABLE webhook_deliveries (
    provider    text NOT NULL,
    delivery_id text NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (provider, delivery_id)
);

-- Terminal failures worth keeping: payloads that authenticated fine but can
-- never be processed (unknown vocabulary, invalid structure). A lightweight
-- dead-letter table instead of a broker.
CREATE TABLE dead_letter_events (
    id          uuid PRIMARY KEY,
    source      text NOT NULL,
    reason      text NOT NULL,
    payload     bytea NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX dead_letter_received_idx ON dead_letter_events (received_at DESC);
